# Generated by Django 3.2.4 on 2024-08-02 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('created_by', models.UUIDField(blank=True, null=True, verbose_name='created by')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('updated_by', models.UUIDField(blank=True, null=True, verbose_name='updated by')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='delete')),
                ('fullname', models.CharField(max_length=100, verbose_name='fullname')),
                ('doctor_no', models.CharField(max_length=100, verbose_name='doctor no')),
                ('sex', models.CharField(blank=True, max_length=1, null=True, verbose_name='sex')),
                ('type', models.CharField(blank=True, max_length=1, null=True, verbose_name='type')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Doctor',
                'db_table': 'c_doctor',
                'ordering': ('-fullname',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='IntegrationApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('created_by', models.UUIDField(blank=True, null=True, verbose_name='created by')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('updated_by', models.UUIDField(blank=True, null=True, verbose_name='updated by')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='delete')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('token', models.CharField(max_length=255, verbose_name='token')),
                ('expired_date', models.DateField(verbose_name='expired date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Integration App',
                'db_table': 'c_integration_app',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('created_by', models.UUIDField(blank=True, null=True, verbose_name='created by')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('updated_by', models.UUIDField(blank=True, null=True, verbose_name='updated by')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='delete')),
                ('order_no', models.CharField(max_length=100, verbose_name='order no')),
                ('order_time', models.DateTimeField(verbose_name='order time')),
                ('accession_no', models.CharField(max_length=100, verbose_name='accession no')),
                ('req_dept_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='requested dept code')),
                ('req_dept_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='requested dept code')),
                ('clinical_diagnosis', models.CharField(blank=True, max_length=255, null=True, verbose_name='clinical diagnosis')),
                ('patient_class', models.CharField(blank=True, max_length=1, null=True, verbose_name='patient class')),
                ('modality_type', models.CharField(max_length=5, verbose_name='modality type')),
                ('is_insurance', models.BooleanField(default=False, verbose_name='is insurance')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='is urgent')),
            ],
            options={
                'verbose_name': 'Order',
                'db_table': 'c_order',
                'ordering': ('-created_at',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('created_by', models.UUIDField(blank=True, null=True, verbose_name='created by')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('updated_by', models.UUIDField(blank=True, null=True, verbose_name='updated by')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='delete')),
                ('pid', models.CharField(max_length=100, verbose_name='pid')),
                ('fullname', models.CharField(max_length=100, verbose_name='fullname')),
                ('sex', models.CharField(blank=True, max_length=1, null=True, verbose_name='sex')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='dob')),
                ('address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='address')),
                ('insurance_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='insurance number')),
            ],
            options={
                'verbose_name': 'Patient',
                'db_table': 'c_patient',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('created_by', models.UUIDField(blank=True, null=True, verbose_name='created by')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('updated_by', models.UUIDField(blank=True, null=True, verbose_name='updated by')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='delete')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.order')),
            ],
            options={
                'verbose_name': 'Procedure',
                'db_table': 'c_procedure',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProcedureType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('created_by', models.UUIDField(blank=True, null=True, verbose_name='created by')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('updated_by', models.UUIDField(blank=True, null=True, verbose_name='updated by')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='delete')),
                ('code', models.CharField(max_length=100, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'ProcedureType',
                'db_table': 'c_procedure_type',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('created_by', models.UUIDField(blank=True, null=True, verbose_name='created by')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('updated_by', models.UUIDField(blank=True, null=True, verbose_name='updated by')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='delete')),
                ('accession_no', models.CharField(max_length=100, verbose_name='accession no')),
                ('study_iuid', models.CharField(max_length=100, verbose_name='study instance uid')),
                ('findings', models.TextField(blank=True, null=True, verbose_name='findings')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='conclusion')),
                ('status', models.CharField(max_length=1, verbose_name='status')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.procedure')),
                ('radiologist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.doctor')),
            ],
            options={
                'verbose_name': 'Report',
                'db_table': 'c_report',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='procedure',
            name='procedure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.proceduretype'),
        ),
        migrations.AddField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.patient'),
        ),
        migrations.AddField(
            model_name='order',
            name='referring_phys',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='account.doctor'),
        ),
    ]
