# Generated by Django 3.2.4 on 2024-08-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20240802_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sex',
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, default='U', max_length=1, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, default='U', max_length=1, null=True, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='report',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.procedure'),
        ),
    ]
