# Generated by Django 3.2.4 on 2024-08-02 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_patient_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='referring_phys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.doctor'),
        ),
    ]
