# Generated by Django 3.2.4 on 2024-08-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_is_insurance_order_is_insurance_applied'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('accession_no', 'delete_flag')},
        ),
    ]
