# Generated by Django 3.2.4 on 2024-08-06 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_order_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationapp',
            name='representer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
