# Generated by Django 3.2.4 on 2024-08-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_integrationapp_representer'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='sign',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sign'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='integrationapp',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='proceduretype',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='date modified'),
        ),
    ]
