# Generated by Django 3.2.4 on 2024-08-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20240808_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sign',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sign'),
        ),
    ]
