# Generated by Django 3.2.4 on 2024-08-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20240808_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='study_iuid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='study instance uid'),
        ),
    ]
