# Generated by Django 3.2.4 on 2024-08-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_procedure_study_iuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tel'),
        ),
    ]
