# Generated by Django 3.2.4 on 2024-08-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_patient_tel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('accession_no', 'procedure', 'delete_flag')},
        ),
    ]
