# Generated by Django 3.2.4 on 2024-08-23 11:30

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('created_by', models.UUIDField(blank=True, null=True, verbose_name='created by')),
                ('updated_at', models.DateTimeField(editable=False, null=True, verbose_name='date modified')),
                ('updated_by', models.UUIDField(blank=True, null=True, verbose_name='updated by')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='delete')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('findings', models.TextField(verbose_name='findings')),
                ('conclusion', models.TextField(verbose_name='conclusion')),
                ('type', models.CharField(default='custom', max_length=6, verbose_name='type')),
                ('modality', models.CharField(max_length=5, verbose_name='modality')),
            ],
            options={
                'verbose_name': 'Report Template',
                'db_table': 'c_report_template',
                'ordering': ('-name',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
