# Generated by Django 3.2.4 on 2024-08-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reporttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='patient_class',
            field=models.CharField(blank=True, default='U', max_length=1, null=True, verbose_name='patient class'),
        ),
        migrations.AlterField(
            model_name='order',
            name='req_dept_code',
            field=models.CharField(max_length=100, verbose_name='requested dept code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='req_dept_name',
            field=models.CharField(max_length=100, verbose_name='requested dept name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='dob'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_no',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='insurance number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tel',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Tel'),
        ),
    ]
