# Generated by Django 3.2.4 on 2024-08-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20240824_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='clinical_diagnosis',
            field=models.CharField(max_length=2000, verbose_name='clinical diagnosis'),
        ),
    ]
