# Generated by Django 3.2.4 on 2024-08-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_order_clinical_diagnosis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttemplate',
            options={'default_permissions': (), 'ordering': ('name',), 'permissions': (), 'verbose_name': 'Report Template'},
        ),
    ]
