# Generated by Django 3.2.4 on 2024-08-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_reporttemplate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='doctor no'),
        ),
    ]
