# Generated by Django 3.2.4 on 2024-09-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20240831_1919'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
    ]
