# Generated by Django 3.2.4 on 2024-09-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_alter_report_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
    ]
