# Generated by Django 3.2.4 on 2024-09-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_alter_report_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('delete_flag', False)), fields=('accession_no', 'procedure'), name='unique_report_procedure'),
        ),
    ]
