# Generated by Django 3.2.4 on 2024-10-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_alter_doctor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'default_permissions': (), 'ordering': ('-created_at',), 'permissions': (), 'verbose_name': 'Report'},
        ),
    ]
