# Generated by Django 3.2.4 on 2024-10-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_alter_report_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='imaging_scan_type',
            field=models.TextField(blank=True, null=True, verbose_name='imaging scan type'),
        ),
    ]
