# Generated by Django 3.2.4 on 2024-10-31 15:13

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_report_imaging_scan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('created_by', models.UUIDField(blank=True, null=True, verbose_name='created by')),
                ('updated_at', models.DateTimeField(editable=False, null=True, verbose_name='date modified')),
                ('updated_by', models.UUIDField(blank=True, null=True, verbose_name='updated by')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='delete')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('regular', models.TextField(verbose_name='regular')),
                ('by_medicine', models.TextField(blank=True, null=True, verbose_name='by medicine')),
                ('by_disease', models.TextField(blank=True, null=True, verbose_name='by disease')),
                ('modality', models.CharField(max_length=5, verbose_name='modality')),
            ],
            options={
                'verbose_name': 'Scan protocol',
                'db_table': 'c_scan_protocol',
                'ordering': ('name',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
