# Generated by Django 3.2.4 on 2024-10-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_scanprotocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='imaging_scan_type',
        ),
        migrations.AddField(
            model_name='report',
            name='scan_protocol',
            field=models.TextField(blank=True, null=True, verbose_name='scan protocol'),
        ),
    ]
