# Generated by Django 3.2.4 on 2024-11-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_auto_20241031_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='status',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='study_num_instances',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of instances'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='study_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='study time'),
        ),
    ]
